management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: todo-ai-service

security:
  jwt:
    secret-key: ${JWT_SECRET:dHEzSngqQ25DI3IyXkcmNUd5dXglNiZ1NUc1OUFOYiY=}

llm:
  secrets:
    api-key: ${LLM_SECRETS_API_KEY:2F6D11A5D62B00197B492E3D:c31ff47ca3d7b2a48c5287a291f8028f}
    user-id: ${LLM_SECRETS_USER_ID:2F6D11A5D62B00197B492E3D}

api-gateway:
  url: ${API_GATEWAY_URL:http://localhost:8080}

server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /api/v1/ai

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8081/eureka}